config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :email_lists
  root to: 'email_lists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  validates :address, presence: true
  belongs_to :email_list
end

app/models/email_list.rb
class EmailList < ApplicationRecord

  validates :name, :email_column, presence: true

  has_many :emails, dependent: :destroy
  has_one_attached :email_csv
  has_one_attached :filtered_email_csv

end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  # validates :name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :email_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/email_lists_controller.rb
class EmailListsController < ApplicationController
  before_action :authenticate_user!
  def index
    @email_lists = EmailList.where(user_id: current_user.id)
  end

  def new
    @email_list = EmailList.new
  end

  def show
    @email_list = EmailList.find_by(user_id: current_user.id, id: params[:id])
    @emails = @email_list.emails.page params[:page]
  end

  def create
    params = email_list_params
    params[:name] = params[:email_csv].original_filename.split(".csv").first unless params[:name].present?
    email_list = EmailList.new(params.merge(user_id: current_user.id))

    if email_list.save!
      
      FilterEmailJob.perform_later(email_list.id)
      redirect_to email_list, notice: "Email list was imported sucessfully"
    else
      render :new
    end
  end

  def edit
  end

  def update

  end

  def destroy
  end

  private

  def email_list_params
    params.require(:email_list).permit(:name, :email_column, :email_csv)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/email_lists/index.html.erb
<% if @email_lists.any?%>
  <h2 class="text-center"> 
    Uploaded Email Lists
  </h2>

  <table class="table mt-5">
    <thead class="thead-light">
      <tr>
        <th scope="col">List Name</th>
        <th class="text-center" scope="col">Number of Record </th>
        <th class="text-center" scope="col">Verification Status</th>
        <th class="text-center" scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @email_lists.each do |list| %>
        <tr>
          <th scope="row"> <%= list.name %> </th>
          <td class="text-center"> <%= list.emails.count %> </td>
          <td class="text-center"> <%= list.verified ? "Verified" : "Not Verified" %> </td>
          <td class="text-center"> <%= link_to("Show", list) %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>

  <div class="alert text-center alert-info" role="alert">
    Looks like your Email list is empty.
    <br/>
    Go ahead, Upload and and get them analyzed
  </div>
<% end %>

app/views/email_lists/new.html.erb
<h2 class="text-center"> Upload CSV file to analyze </h2>
<div>
<%= form_for @email_list, url: email_lists_path do |f| %>
    <div class="form-group">
      <%= f.label :name, "List Name" %>
      <%= f.text_field :name, class: "form-control", placeholder: 'Skip to let us infer from file name' %>
    </div>
    <div class="form-group">
      <%= f.label :name, "Email Column" %>
      <%= f.text_field :email_column, class: "form-control", placeholder: '* Name of the email column on the CSV', required: true %>
    </div>
   <div class="form-group">
      <%= f.file_field :email_csv, class: 'form-control-file', required: true %>
   </div>
   <%= f.submit "Upload", class: "btn btn-primary" %>
<% end %>
</div>

app/views/email_lists/show.html.erb
<h2 class="text-center"> 
  <span class="font-italic"> <%= @email_list.name %> </span>
  <% if @email_list.verified? %>
    is presented below
  <% else %>
    is being analyzed, will be ready in a while. Please come back later.
  <% end %>  
</h2>
<% if @email_list.verified? %>
<%= link_to('Download Filtered CSV', rails_blob_path(@email_list.filtered_email_csv, disposition: "attachment"), class: 'btn btn-primary')%>
  <table class="table mt-5">
    <thead class="thead-light">
      <tr>
        <th scope="col">Email</th>
        <th class="text-center" scope="col">Valid </th>
      </tr>
    </thead>
    <tbody>
      <% @emails.each do |email| %>
        <tr>
          <th scope="row"> <%= email.address %> </th>
          <td class="text-center"> <%= email.is_valid ? "Yes" : "NO" %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @emails %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleanEmail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="top-navbar-container">
      <div class="top-navbar container-fluid">
        <div class="row">
        <div class="col-2"></div>
        <div class="col no-left-padding">
            <nav class="navbar no-left-padding navbar-light">
              <a class="navbar-brand">Clean Email</a>
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "ce-logout") %>
              <% else %>
                <%= link_to('Login', new_user_session_path, class: "ce-logout") %>
              <% end %>
            </nav>
          </div>
        </div>
      </div>
    </div>
      <div class="container-fluid">
      <div class="row">
        <div class="col-2 no-left-padding">
          <nav class="menu" tabindex="0">            
            <ul>
              <li class="icon-dashboard"><span><%= link_to("Email Lists", email_lists_path) %></span></li>
              <li class="icon-customers"><span><%= link_to("Upload CSV", new_email_list_url) %></span></li>
              <li class="icon-settings"><span><%= link_to("Settings", root_path) %></span></li>
            </ul>
          </nav>
        </div>
        <div class="col">
        
          <main>
            <% if alert %>
              <div class="alert alert-danger" role="alert">
                <%= alert %>
              </div>
            <% end %>

            <% if notice %>
              <div class="alert alert-primary" role="alert">
                <%= notice %>
              </div>
            <% end %>
            <%= yield %>
          </main>
        </div>
      </div>
    </div>





  
  </body>
</html>